version: '3'

services:
  canchu:
    container_name: canchu_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
      # - mysql
      # - redis
    networks:
      - canchu-network
    command: sh -c "while ! nc -z database.candgzbghgho.us-east-1.rds.amazonaws.com 3306; do sleep 1; done && node app.js"

  # redis:
  #   container_name: canchu-redis
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - canchu-network


  # mysql:
  #   image: mysql:latest
  #   container_name: canchu_mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #   volumes:
  #   - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - canchu-network

  nginx:
    image: nginx:latest
    container_name: canchu-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./private/certificate.crt:/etc/nginx/certificate.crt:ro
      - ./private/private.key:/etc/nginx/private.key:ro
    depends_on:
      - canchu
    networks:
      - canchu-network

networks:
  canchu-network:
    driver: bridge
